cite 'about-alias'
about-alias 'maven abbreviations'

alias mci='mvn clean install'
alias mi='mvn install'
alias mcp='mvn clean package'
alias mp='mvn package'
alias mrprep='mvn release:prepare'
alias mrperf='mvn release:perform'
alias mrrb='mvn release:rollback'
alias mdep='mvn dependency:tree'
alias mpom='mvn help:effective-pom'
#alias mcisk='mci -Dmaven.test.skip=true'
alias mcisk='mci -DskipTests'
alias mcpsk='mcp -Dmaven.test.skip=true'

alias mct='mvn clean test'
alias mctd='mct -Dmaven.surefire.debug="-Xdebug -Xrunjdwp:transport=dt_socket,address=9000,server=y,suspend=y"'

alias mcdsk='mvn clean deploy -DskipTests'
